version: '3.8'

services:
  mongodb:
    image: mongo:5.0
    container_name: news-aggregator-mongodb
    ports:
      - '27017:27017'
    volumes:
      - mongodb_data:/data/db
    environment:
      - MONGO_INITDB_DATABASE=news_aggregator
    restart: unless-stopped
    networks:
      - news-aggregator-network

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: news-aggregator-backend
    ports:
      - '8000:8000'
    depends_on:
      - mongodb
    environment:
      - MONGO_URI=mongodb://mongodb:27017
      - MONGO_DB=news_aggregator
      - MONGO_COLLECTION=news_articles
      - FETCH_INTERVAL_MINUTES=60
      - NEWS_API_KEY=${NEWS_API_KEY:-}
      - HUGGINGFACE_API_KEY=${HUGGINGFACE_API_KEY:-}
    volumes:
      - ./backend/app:/app
    restart: unless-stopped
    networks:
      - news-aggregator-network

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: news-aggregator-frontend
    ports:
      - '5173:80'
    depends_on:
      - backend
    environment:
      - VITE_API_URL=http://localhost:8000
    restart: unless-stopped
    networks:
      - news-aggregator-network

volumes:
  mongodb_data:

networks:
  news-aggregator-network:
    driver: bridge
